### ISSUE TITLE
Helper functions for models

### ISSUE THREAD

**Issue by thinking-tower** [cbrom/Go-LMS#16]
- [x] Course Author
    - [x] `GetCourse()`
    - [x] `GetUser()`
    - [x] `GetCertificates()`

- [x] Student Course
    - [x] `GetStudent()`
    - [x] `GetCourse()`

- [x] Level 
    - [x] `GetCourse()`
    - [x] `GetTargetGroups()`

- [x] Target Groups
    - [x] `GetLevel()`
    - [x] `GetTargets`

- [x] Target Version
    - [x] `GetTarget()`
    - [x] `GetContentBlocks()`

- [x] Target
    - [x] `GetTargetGroup()`
    - [x] `GetTargetVersions()`
    - [x] `GetQuizzes()`

- [x] Content Block
    - [x] `GetTargetVersion()`

- [x] Evaluation Criteria
    - [x] `GetCourse()`

- [x] Quiz
    - [x] `GetTarget()`
    - [x] `GetQuestions()`

- [x] Quiz Question
    - [x] `GetQuiz()`
    - [x] `GetAnswers()`
    - [x] `GetAnswer()`

- [x] Answer Options
    - [x] `GetQuestion()`

- [x] User Answer
    - [x] `GetQuestion()`
    - [x] `GetAnswer()`
    - [x] `GetUser()`

- [x] Certificate
    - [x] `GetCourse()`
    - [x] `GetIssuer()`
    - [x] `GetIssuedCertificates()`

- [x] Issued Certificate
    - [x] `GetCertificate()`
    - [x] `GetUser()`

**Comment by cbrom** [comment]
my assumption is that one course can have multiple authors
